'org.worklogic.db.DatabaseUser'('org.worklogic.db.prolog.PrologHashMap'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(0, []), sa, '', nil, false, false, nil, nil).
'org.worklogic.db.DatabaseClass'('Point', '', false, 'Point', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(3, ['org.worklogic.db.prolog.PrologHashMap$HashEntry'(x, 'org.worklogic.db.DatabaseField'(x, '', 1, 'java.lang.String', false, 'Point.x', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(y, 'org.worklogic.db.DatabaseField'(y, '', 2, 'java.lang.String', false, 'Point.y', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(id, 'org.worklogic.db.DatabaseField'(id, '', 0, 'java.lang.Integer', false, 'Point.id', false, true, false, nil, nil, nil, nil, nil)), nil, nil, nil])).
'org.worklogic.db.DatabaseClass'('Segment', '', false, 'Segment', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(3, ['org.worklogic.db.prolog.PrologHashMap$HashEntry'(poin0, 'org.worklogic.db.DatabaseField'(poin0, '', 1, 'org.worklogic.domain.geometry.Point', false, 'Segment.poin0', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(poin1, 'org.worklogic.db.DatabaseField'(poin1, '', 2, 'org.worklogic.domain.geometry.Point', false, 'Segment.poin1', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(id, 'org.worklogic.db.DatabaseField'(id, '', 0, 'java.lang.Integer', false, 'Segment.id', false, true, false, nil, nil, nil, nil, nil)), nil, nil, nil])).
'org.worklogic.db.DatabaseClass'('Polygon', '', false, 'Polygon', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(4, [nil, nil, nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(id, 'org.worklogic.db.DatabaseField'(id, '', 0, 'java.lang.Integer', false, 'Polygon.id', false, true, false, nil, nil, nil, nil, nil)), nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(segment0, 'org.worklogic.db.DatabaseField'(segment0, '', 1, 'org.worklogic.domain.geometry.Segment', false, 'Polygon.segment0', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(segment1, 'org.worklogic.db.DatabaseField'(segment1, '', 2, 'org.worklogic.domain.geometry.Segment', false, 'Polygon.segment1', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(segment2, 'org.worklogic.db.DatabaseField'(segment2, '', 3, 'org.worklogic.domain.geometry.Segment', false, 'Polygon.segment2', false, false, false, nil, nil, nil, nil, nil))])).
'org.worklogic.db.DatabaseClass'('Tetragon', '', false, 'Tetragon', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(1, ['org.worklogic.db.prolog.PrologHashMap$HashEntry'(segment3, 'org.worklogic.db.DatabaseField'(segment3, '', 0, 'org.worklogic.domain.geometry.Segment', false, 'Tetragon.segment3', false, false, false, nil, nil, nil, nil, nil)), nil])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fn, '', 'dat/hierarchical/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fni, '', 'dat/hierarchical/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fnj, '', 'dat/hierarchical/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fnk, '', 'dat/hierarchical/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.DatabaseSequence'(point_sequence, '', 0, 'org.worklogic.domain.geometry.Point', 1).
'org.worklogic.db.DatabaseSequence'(segment_sequence, '', 0, 'org.worklogic.domain.geometry.Segment', 1).
'org.worklogic.db.DatabaseSequence'(polygon_sequence, '', 0, 'org.worklogic.domain.geometry.Polygon', 1).
'org.worklogic.db.DatabaseSequence'(tetragon_sequence, '', 0, 'org.worklogic.domain.geometry.Tetragon', 1).
'org.worklogic.db.prolog.PrologDatabaseView'('org.worklogic.domain.geometry.view.SamePoint', '', 'dat/hierarchical/test/views.pl', 'org.worklogic.db.prolog.PrologArrayList'(3, ['Idp', 'X', 'Y'])).
