'org.worklogic.db.DatabaseUser'('org.worklogic.db.prolog.PrologHashMap'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(0, []), sa, '', nil, false, false, nil, nil).
'org.worklogic.db.DatabaseClass'('Address', '', false, 'Address', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(5, [nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(city, 'org.worklogic.db.DatabaseField'(city, '', 1, 'java.lang.String', false, 'Address.city', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(country, 'org.worklogic.db.DatabaseField'(country, '', 4, 'java.lang.String', false, 'Address.country', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(street, 'org.worklogic.db.DatabaseField'(street, '', 0, 'java.lang.String', false, 'Address.street', false, false, false, nil, nil, nil, nil, nil)), nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(state, 'org.worklogic.db.DatabaseField'(state, '', 2, 'java.lang.String', false, 'Address.state', false, false, false, nil, nil, nil, nil, nil)), nil, nil, nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(zip, 'org.worklogic.db.DatabaseField'(zip, '', 3, 'java.lang.String', false, 'Address.zip', false, false, false, nil, nil, nil, nil, nil))])).
'org.worklogic.db.DatabaseClass'('Person', '', false, 'Person', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(12, ['org.worklogic.db.prolog.PrologHashMap$HashEntry'(joinDate, 'org.worklogic.db.DatabaseField'(joinDate, '', 9, 'java.util.Date', false, 'Person.joinDate', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(lastLoginDate, 'org.worklogic.db.DatabaseField'(lastLoginDate, '', 10, 'java.util.Date', false, 'Person.lastLoginDate', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(loginCount, 'org.worklogic.db.DatabaseField'(loginCount, '', 11, 'java.lang.Integer', false, 'Person.loginCount', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(birthDate, 'org.worklogic.db.DatabaseField'(birthDate, '', 8, 'java.util.Date', false, 'Person.birthDate', false, false, false, nil, nil, nil, nil, nil)), nil, nil, nil, nil, nil, nil, nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(phones, 'org.worklogic.db.DatabaseField'(phones, '', 5, 'java.util.List', false, 'Person.phones', false, false, false, 'java.lang.String', nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(nickNames, 'org.worklogic.db.DatabaseField'(nickNames, '', 7, 'java.util.Set', false, 'Person.nickNames', false, false, false, 'java.lang.String', nil, nil, nil, nil)), nil, nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(lastName, 'org.worklogic.db.DatabaseField'(lastName, '', 3, 'java.lang.String', false, 'Person.lastName', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(middleName, 'org.worklogic.db.DatabaseField'(middleName, '', 2, 'java.lang.String', false, 'Person.middleName', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(emails, 'org.worklogic.db.DatabaseField'(emails, '', 6, 'java.util.Collection', false, 'Person.emails', false, false, false, 'java.lang.String', nil, nil, nil, nil)), nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(firstName, 'org.worklogic.db.DatabaseField'(firstName, '', 1, 'java.lang.String', false, 'Person.firstName', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(address, 'org.worklogic.db.DatabaseField'(address, '', 4, 'org.worklogic.domain.model.Address', false, 'Person.address', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(id, 'org.worklogic.db.DatabaseField'(id, '', 0, 'java.lang.Integer', false, 'Person.id', false, true, false, nil, nil, nil, nil, nil)), nil, nil])).
'org.worklogic.db.DatabaseClass'('Employee', '', false, 'Employee', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(2, [nil, nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(salary, 'org.worklogic.db.DatabaseField'(salary, '', 0, 'java.lang.Long', false, 'Employee.salary', false, false, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(department, 'org.worklogic.db.DatabaseField'(department, '', 1, 'org.worklogic.domain.model.Department', false, 'Employee.department', false, false, false, nil, nil, nil, nil, nil))])).
'org.worklogic.db.DatabaseClass'('Department', '', false, 'Department', false, '', 'org.worklogic.db.prolog.PrologArrayList'(0, []), 'org.worklogic.db.prolog.PrologHashMap'(3, [nil, 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(id, 'org.worklogic.db.DatabaseField'(id, '', 0, 'java.lang.Integer', false, 'Department.id', false, true, false, nil, nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(employeesByCubicle, 'org.worklogic.db.DatabaseField'(employeesByCubicle, '', 2, 'java.util.Map', false, 'Department.employeesByCubicle', false, false, false, 'org.worklogic.domain.model.Employee', nil, nil, nil, nil)), 'org.worklogic.db.prolog.PrologHashMap$HashEntry'(name, 'org.worklogic.db.DatabaseField'(name, '', 1, 'java.lang.String', false, 'Department.name', false, false, false, nil, nil, nil, nil, nil)), nil, nil])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fn, '', 'dat/relational/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fni, '', 'dat/relational/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fnj, '', 'dat/relational/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.prolog.PrologDatabaseFunction'(fnk, '', 'dat/relational/test/functions.pl', 'org.worklogic.db.prolog.PrologArrayList'(4, ['X', 'Y', 'Z', 'R'])).
'org.worklogic.db.DatabaseSequence'(adddress_sequence, '', 0, 'org.worklogic.domain.model.Address', 1).
'org.worklogic.db.DatabaseSequence'(person_sequence, '', 0, 'org.worklogic.domain.model.Person', 1).
'org.worklogic.db.DatabaseSequence'(employee_sequence, '', 0, 'org.worklogic.domain.model.Employee', 1).
'org.worklogic.db.DatabaseSequence'(department_sequence, '', 0, 'org.worklogic.domain.model.Department', 1).
'org.worklogic.db.prolog.PrologDatabaseView'('org.worklogic.domain.model.view.AnEmployeeView', '', 'dat/relational/test/views.pl', 'org.worklogic.db.prolog.PrologArrayList'(14, ['Salary', 'Department', 'Id', 'FirstName', 'MiddleName', 'LastName', 'Address', 'Phones', 'Emails', 'NickNames', 'BirthDate', 'JoinDate', 'LastLoginDate', 'LoginCount'])).
